echo "current path setting:$PATH"
echo "current working directory:`pwd`"
echo "os type:$OSTYPE"
echo "release number:`uname -r`"
echo "kernel name:`uname -s`"
echo "kernel version:`uname -v`"
echo "all available shells:`cat /etc/shells`"
echo "cpu "info":`cat /proc/cpuinfo`"
echo "memory "info":`cat /proc/meminfo`"
echo "harddisk "indo":`lsblk`"

